-- Seed state homeschool requirements data
-- This data is based on general homeschooling regulations as of 2024

INSERT INTO state_requirements (state_abbreviation, state_name, subjects_required, hours_per_year, attendance_rules, assessment_requirements, record_keeping_requirements, special_needs_provisions, early_childhood_rules, high_school_rules, additional_info) VALUES

('AL', 'Alabama', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Must provide a program of study in prescribed subjects. 180 school days required.', 'Annual standardized test or portfolio review', 'Maintain records of subjects studied and materials used', 'Must follow 504 Plan or IEP if student previously identified', 'Ages 5-6 may be exempt if student is academically not ready', 'Must meet Carnegie unit requirements for high school credits', '{"note":"Very homeschool friendly state"}'::jsonb),

('AK', 'Alaska', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 900, 'Parent must be certified teacher or program must be approved. Minimum 900 hours per year.', 'Must demonstrate mastery through testing or portfolio', 'Keep records of curriculum and student progress', 'IEP and 504 Plans must be followed', 'No specific early childhood requirements', 'Must meet Alaska State standards', '{"note":"Requires parental approval or certified teacher"}'::jsonb),

('AZ', 'Arizona', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Notify district of intent. Equivalent instruction required.', 'Annual assessment required (test, evaluation, or portfolio)', 'Portfolio or records of progress', 'Services may be required if student has disability', 'Preschool students not required', 'Must issue diploma or transcript', '{"note":"Very flexible homeschooling regulations"}'::jsonb),

('AR', 'Arkansas', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 900, 'Annual approval required. Curriculum must be approved by state.', 'Annual standardized achievement test required', 'Maintain documented curriculum and attendance records', 'Must comply with IDEA if applicable', 'No specific early childhood requirements', 'Approved curriculum required, transcript issued', '{"note":"Curriculum approval required"}'::jsonb),

('CA', 'California', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Essentially unregulated if parent is teacher. If using private school affidavit, specific rules apply.', 'Private school affidavit option allows self-directed education', 'Keep curriculum materials and workbooks', 'Services may be available if child is eligible', 'Preschool not regulated', 'Can graduate as private school or use charter options', '{"note":"One of most homeschool friendly states"}'::jsonb),

('CO', 'Colorado', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1000, 'File intent form annually. 1000 hours instruction time required.', 'Standardized test or portfolio review required annually', 'Keep attendance records and curriculum materials', 'Must follow special education requirements if applicable', 'No specific requirements for ages before K', 'State standards must be included in high school curriculum', '{"note":"Moderate requirements, very organized state"}'::jsonb),

('CT', 'Connecticut', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies', 'Physical Education'], 1000, 'Prior written approval from Commissioner. 1000 hours per year.', 'Annual testing with standardized test', 'Quarterly narrative reports of progress', 'Must accommodate IEP or 504 plan', 'Age 5 may homeschool with written approval', 'Must meet state standards for coursework', '{"note":"Requires prior approval and testing"}'::jsonb),

('DE', 'Delaware', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Prior notification to district. Maintain equivalent instruction.', 'Annual standardized test or evaluation required', 'Maintain attendance records and portfolio', 'Must follow IDEA and Section 504', 'No specific early childhood requirements', 'Accreditation or evaluation required', '{"note":"Relatively moderate requirements"}'::jsonb),

('FL', 'Florida', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File declaration of intent. Provide sequential, progressive instruction.', 'Annual standardized assessment required (can use multiple options)', 'Maintain portfolio of work and attendance records', 'Services available if student qualifies', 'Kindergarten and below not required', 'Must meet Florida standards', '{"note":"Very flexible with portfolio options"}'::jsonb),

('GA', 'Georgia', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Provide written curriculum. Three option pathway available.', 'Annual assessment via standardized test or evaluation', 'Maintain detailed attendance records and curriculum plan', 'Must provide or find services for special education', 'Ages 5-6 may be exempt if not ready', 'Can use virtual schools or independent study', '{"note":"Three pathway system for flexibility"}'::jsonb),

('HI', 'Hawaii', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies', 'Hawaiian Culture'], NULL, 'Submit curriculum and student records. Hawaiian culture must be included.', 'Assessment by approved evaluator at grades 3, 6, 8, 10', 'Transcript and documentation of learning', 'Services must be provided if student eligible', 'Kindergarten curriculum must include Hawaiian', 'Transcripts must be maintained', '{"note":"Hawaiian culture requirement is unique"}'::jsonb),

('ID', 'Idaho', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File notice of intent with district. Maintain equivalent instruction.', 'Annual assessment in reading, math, and language arts', 'Keep records of instruction and evaluation results', 'Must serve students with disabilities', 'Age 5 must enroll in kindergarten or file notice', 'Course credits and grades must be maintained', '{"note":"Homeschool friendly with minimal requirements"}'::jsonb),

('IL', 'Illinois', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 176, 'File form with school district. 176 school days minimum.', 'Annual assessment in reading, math, language arts, science', 'Maintain evidence of instruction and assessment', 'May qualify for IEP through public school', 'No specific early childhood requirements', 'Transcript required for high school graduation', '{"note":"Requires minimum 176 days of instruction"}'::jsonb),

('IN', 'Indiana', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Notify school of intent to homeschool. Follow state standards.', 'Assessment method of parent choice (test, portfolio, evaluation)', 'Maintain curriculum, materials, and records', 'Services available through public school if eligible', 'Preschool years not regulated', 'Must maintain transcript', '{"note":"Flexible assessment options available"}'::jsonb),

('IA', 'Iowa', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 876, 'Submit curriculum in advance. Parent must have high school diploma or qualified teacher.', 'Annual assessment required', 'Maintain detailed records of instruction and curriculum', 'Services may be available if student qualifies', 'Age 5 must enroll', 'Transcript required', '{"note":"Requires advance curriculum approval"}'::jsonb),

('KS', 'Kansas', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File written notice. Equivalent instruction required.', 'Assessment by approved evaluator (portfolio or test)', 'Maintain documentation of instruction', 'Special education coordination available', 'No specific early childhood requirement', 'Credits and transcript required', '{"note":"Homeschool friendly with clear pathways"}'::jsonb),

('KY', 'Kentucky', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 700, 'File Notice of Intent. Minimum 700 hours of instruction.', 'Option for standardized test, portfolio review, or evaluation', 'Maintain records of student progress and curriculum', 'Services available through public school', 'Age 6 begins requirement', 'Transcripts must be maintained', '{"note":"Moderate requirements, clear structure"}'::jsonb),

('LA', 'Louisiana', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'Register with state. 180 school days per year.', 'Annual standardized test required', 'Maintain curriculum documentation and attendance', 'Services must be provided if applicable', 'Ages 5-6 enrolled if they meet requirements', 'Grade 11 assessment required', '{"note":"Requires standardized testing"}'::jsonb),

('ME', 'Maine', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 175, 'File Notice of Intent. Minimum 175 days per year.', 'Annual assessment via portfolio or standardized test', 'Quarterly progress reports to superintendent', 'Services available if student qualifies', 'Kindergarten requirement age 5', 'Transcripts required', '{"note":"Regular communication with school required"}'::jsonb),

('MD', 'Maryland', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1080, 'File form with local school board. 1080 hours per year.', 'Standardized test annually OR portfolio AND evaluation every 3 years', 'Maintain attendance and progress records', 'Services must be provided if student eligible', 'Age 5 kindergarten or homeschool with documentation', 'Transcripts and progress required', '{"note":"Structured requirements with testing focus"}'::jsonb),

('MA', 'Massachusetts', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Submit education plan to superintendent. Equivalent instruction.', 'Annual assessment via standardized test or approved alternative', 'Maintain records of instruction and assessment', 'Services required for students with disabilities', 'Age 6 must begin education', 'Transcript required', '{"note":"Plan must be submitted and approved"}'::jsonb),

('MI', 'Michigan', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File with school district. Equivalent instruction in taught subjects.', 'Assessment method of parent choice', 'Maintain curriculum and records', 'Coordinate with school district on special education', 'No specific early childhood requirements', 'Can graduate as homeschooled student', '{"note":"Very homeschool friendly state"}'::jsonb),

('MN', 'Minnesota', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1080, 'Notify school. 1080 hours instruction required.', 'Annual standardized test in grades 3, 5, and 8-12', 'Keep curriculum and attendance records', 'Services available through school district', 'Ages 5-6 not required if parent teaches', 'Transcripts required for high school', '{"note":"1080 hour requirement is specific"}'::jsonb),

('MS', 'Mississippi', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'File with school district. 180 school days.', 'Annual assessment via standardized test', 'Maintain attendance and student records', 'Services may be available if student qualifies', 'Age 5 begins kindergarten requirement', 'Credits and grades must be recorded', '{"note":"Clear 180 day requirement"}'::jsonb),

('MO', 'Missouri', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1000, 'Register with school district. 1000 hours per year (K-8) or 2000+ for high school.', 'Annual assessment via standardized test or evaluation by professional', 'Maintain curriculum materials and student records', 'Services available for students with disabilities', 'Ages 5-6 may participate in school programs', 'High school requires transcript', '{"note":"Hour-based requirement varies by grade"}'::jsonb),

('MT', 'Montana', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File with school district. Implement school program.', 'Assessment method of choice (test, portfolio, evaluation)', 'Maintain records of curriculum and instruction', 'Services available if student qualifies', 'Age 7 starts requirement', 'Transcript required', '{"note":"Flexible requirements, age 7 start"}'::jsonb),

('NE', 'Nebraska', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1032, 'File Certificate of Attendance. 1032 hours annually.', 'Annual standardized test required (grades 3, 5, 8, 11)', 'Maintain curriculum records and attendance logs', 'Services available for students with identified needs', 'Age 5 must be enrolled in a program', 'Transcript required for graduation', '{"note":"Specific hour requirement and testing"}'::jsonb),

('NV', 'Nevada', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File form with Department of Education. Equivalent instruction.', 'Annual standardized test or evaluation by professional', 'Maintain records of curriculum and assessment results', 'Services may be available if student qualifies', 'Ages 7-17 covered by requirement', 'Can graduate as private school student', '{"note":"Very homeschool friendly"}'::jsonb),

('NH', 'New Hampshire', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Notify superintendent. Equivalent instruction to public school.', 'Assessment via standardized test, portfolio, or professional evaluation', 'Maintain records and provide progress reports quarterly', 'Services available for students with disabilities', 'Age 6 must start (can be homeschool)', 'Transcript required', '{"note":"Flexible with good regulation"}'::jsonb),

('NJ', 'New Jersey', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1200, 'Prior approval from Commissioner of Education required. 1200 hours per year.', 'Annual standardized test required', 'Maintain curriculum documentation', 'Services must be provided under IDEA', 'Age 5 beginning kindergarten', 'Transcripts required', '{"note":"Requires prior Commissioner approval"}'::jsonb),

('NM', 'New Mexico', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File intent. Must provide instruction equivalent to public school.', 'Annual assessment via standardized test or portfolio', 'Maintain curriculum and progress records', 'Services available for students with disabilities', 'Kindergarten (age 5) not required', 'Transcripts and diplomas issued', '{"note":"Relatively flexible requirements"}'::jsonb),

('NY', 'New York', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 900, 'File notice of intent. 900 hours instruction annually.', 'Annual assessment via standardized test or portfolio', 'Quarterly reports and annual assessment required', 'Services available for students with IEP/504', 'Age 6 must begin', 'Regents exams may be required', '{"note":"Structured requirements with specific hours"}'::jsonb),

('NC', 'North Carolina', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1000, 'Register with appropriate party. 1000 hours for elementary, 2500+ for secondary.', 'Annual assessment via standardized test or evaluation', 'Maintain records of student progress and curriculum', 'Services available through school district', 'Ages 7-16 covered', 'High school transcript required', '{"note":"Hour requirements vary by grade level"}'::jsonb),

('ND', 'North Dakota', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1050, 'File with school district. 1050 hours per year.', 'Annual assessment via standardized test or approved evaluation', 'Maintain attendance and curriculum records', 'Services available for students with disabilities', 'Age 7 begins requirement', 'Transcripts required', '{"note":"Clear 1050 hour requirement"}'::jsonb),

('OH', 'Ohio', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 900, 'File intent. Provide instruction in required subjects, 900 hours per year.', 'Annual assessment required (test, evaluation, or portfolio)', 'Maintain records of curriculum and progress', 'Services may be available if student qualifies', 'Ages 5-6 not required to enroll', 'Transcripts required for high school', '{"note":"Flexible with multiple assessment options"}'::jsonb),

('OK', 'Oklahoma', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'File with state. 180 school days per year.', 'Annual assessment required (standardized test or evaluation)', 'Maintain records of school days and curriculum', 'Services available for students with disabilities', 'Ages 5-6 assessed on case-by-case basis', 'Transcripts required', '{"note":"180 day requirement is specific"}'::jsonb),

('OR', 'Oregon', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1260, 'File Certificate of Intent. 1260 hours per year, K-8; 1260+ for 9-12.', 'Annual assessment required in grades 3, 5, 8, and 10-12', 'Maintain attendance records', 'Services available through school district', 'Kindergarten (age 5) required requirement or homeschool', 'Transcripts required', '{"note":"Specific hour requirement and testing grades"}'::jsonb),

('PA', 'Pennsylvania', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'File Certificate of Intent. 180 days of instruction.', 'Annual assessment via standardized test or evaluation by professional', 'Maintain portfolio and progress records', 'Services through school district if student qualifies', 'Age 6 school-age', 'High school transcript required', '{"note":"Reasonable requirements, good support"}'::jsonb),

('RI', 'Rhode Island', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1000, 'File notice and curriculum. 1000 hours per year.', 'Annual assessment via standardized test', 'Maintain curriculum documents and attendance records', 'Services available for eligible students', 'Age 5 kindergarten begins', 'Transcripts required', '{"note":"Clear hour requirement and assessment"}'::jsonb),

('SC', 'South Carolina', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'Notify school district in advance. 180 days per year.', 'Annual standardized test required', 'Maintain attendance and curriculum records', 'Services available for students with disabilities', 'Age 5 begins kindergarten or homeschool', 'Transcripts required', '{"note":"Straightforward requirements"}'::jsonb),

('SD', 'South Dakota', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Notify school district. Equivalent instruction.', 'Annual assessment required (test, portfolio, or evaluation)', 'Maintain records of student progress', 'Services available if student qualifies', 'Ages 5-6 not required', 'Transcript required', '{"note":"Very homeschool friendly state"}'::jsonb),

('TN', 'Tennessee', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1080, 'File affidavit with school. 1080 hours per year.', 'Annual standardized test (option 1) or portfolio review (option 2)', 'Maintain records and assessment documentation', 'Services available for students with disabilities', 'Age 5 may begin kindergarten', 'Transcripts required', '{"note":"Two assessment pathway options"}'::jsonb),

('TX', 'Texas', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Good faith homeschool program legally allowed. Minimal oversight.', 'Minimal assessment requirements; good faith requirement', 'Maintain curriculum and attendance records', 'Services may be available if student qualifies', 'Ages 5-6 may be assessed', 'Can graduate as homeschooled student', '{"note":"Very homeschool friendly, minimal regulation"}'::jsonb),

('UT', 'Utah', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File notice with school. Equivalent instruction.', 'Assessment method of parent choice', 'Maintain records of curriculum and materials', 'Services available for eligible students', 'Ages 5-6 not required', 'Can graduate as homeschooled student', '{"note":"Very flexible, minimal requirements"}'::jsonb),

('VT', 'Vermont', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1000, 'File Notice of Intent. 1000 hours of instruction per year.', 'Annual assessment via standardized test or evaluation', 'Maintain curriculum and progress documentation', 'Services available for students with IEP/504', 'Ages 5-6 early childhood assessment', 'Transcripts required', '{"note":"Clear 1000 hour requirement"}'::jsonb),

('VA', 'Virginia', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'Notify Division Superintendent. Equivalent instruction, 180 school days.', 'Annual assessment via standardized test, evaluation, or portfolio', 'Maintain curriculum records and progress documentation', 'Services available for students with disabilities', 'Ages 5-6 may participate', 'High school standards-based grade report required', '{"note":"Clear structure with flexibility"}'::jsonb),

('WA', 'Washington', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 1000, 'File Parent-Assign Form. Instruction in state standard subjects.', 'Annual assessment (test, portfolio, or evaluation)', 'Maintain curriculum and student records', 'Services may be available if student qualifies', 'Ages 5-6 kindergarten or homeschool', 'Transcript required', '{"note":"Balanced requirements, parent-friendly"}'::jsonb),

('WV', 'West Virginia', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], 180, 'File satement of notice. 180 days per year.', 'Annual assessment via standardized test required', 'Maintain attendance and curriculum records', 'Services available through school system', 'Age 5 begins requirement', 'Transcripts required', '{"note":"Clear 180 day and testing requirement"}'::jsonb),

('WI', 'Wisconsin', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'File form with school district. Equivalent instruction.', 'Annual assessment via standardized test or professional evaluation', 'Maintain curriculum and student records', 'Services available if student qualifies', 'Ages 3-4 not required; age 5+ begin requirement', 'Transcripts required for high school', '{"note":"Very homeschool friendly state"}'::jsonb),

('WY', 'Wyoming', ARRAY['Language Arts', 'Math', 'Science', 'Social Studies'], NULL, 'Homeschooling is allowed under state law with minimal requirements.', 'Must be capable of providing education; no state testing required', 'Maintain basic records', 'Services available through school district', 'No specific early childhood requirements', 'Can graduate as homeschooled student', '{"note":"Minimal regulation, very flexible"}'::jsonb);

-- Verify the data was inserted
SELECT COUNT(*) as total_states FROM state_requirements;
