-- Migration 06: AI Curriculum Advisor — recommendations, objectives, and chat history
-- Supports the Pavved-style AI advisor flow:
--   Stage 1: AI generates curriculum recommendations per child → parent reviews/approves
--   Stage 2: Per approved objective, parent chooses AI-generate or parent-built → track completion

-- Curriculum recommendations (a year plan generated by AI for a specific child)
CREATE TABLE IF NOT EXISTS curriculum_recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id UUID NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  school_year TEXT,              -- e.g. '2026-27'
  grade TEXT,
  status TEXT DEFAULT 'pending', -- pending | reviewed | approved | archived
  tags TEXT[] DEFAULT '{}',      -- e.g. 'Common Core Aligned', 'Charlotte Mason', 'Nature Focus'
  ai_notes TEXT,                 -- AI reasoning / summary for the parent
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Subjects within a recommendation
CREATE TABLE IF NOT EXISTS recommendation_subjects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  recommendation_id UUID NOT NULL REFERENCES curriculum_recommendations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,            -- e.g. 'Mathematics (Common Core)'
  color TEXT DEFAULT '#3b82f6',  -- display color for UI
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Individual objectives within a subject
CREATE TABLE IF NOT EXISTS recommendation_objectives (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  subject_id UUID NOT NULL REFERENCES recommendation_subjects(id) ON DELETE CASCADE,
  recommendation_id UUID NOT NULL REFERENCES curriculum_recommendations(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',  -- pending | approved | rejected | completed
  lesson_source TEXT,             -- null (not yet chosen) | 'ai' | 'parent'
  lesson_packet_id UUID REFERENCES lesson_packets(id) ON DELETE SET NULL,
  parent_notes TEXT,
  sort_order INTEGER DEFAULT 0,
  reviewed_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- AI advisor chat messages (persistent conversation history per user)
CREATE TABLE IF NOT EXISTS advisor_chat_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  child_id UUID REFERENCES children(id) ON DELETE SET NULL,
  role TEXT NOT NULL,            -- 'user' | 'assistant'
  content TEXT NOT NULL,
  structured_data JSONB,        -- rich card data (curriculum outlines, progress cards, etc.)
  message_type TEXT DEFAULT 'text', -- text | curriculum_plan | progress_report | compliance_check | lesson_suggestion
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enhanced state compliance: specific filing requirements per state
-- This extends the existing state_requirements table with actionable filing types
CREATE TABLE IF NOT EXISTS state_filing_types (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  state_abbreviation TEXT NOT NULL,
  filing_name TEXT NOT NULL,       -- e.g. 'Letter of Intent', 'Transfer Request', 'Annual Notification'
  description TEXT,
  frequency TEXT,                  -- 'once' | 'annual' | 'quarterly' | 'as_needed'
  typical_due_description TEXT,    -- e.g. 'Before starting homeschool', 'By September 1 each year'
  form_url TEXT,                   -- link to the official form if available
  is_required BOOLEAN DEFAULT true,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_curriculum_rec_user ON curriculum_recommendations(user_id);
CREATE INDEX IF NOT EXISTS idx_curriculum_rec_child ON curriculum_recommendations(child_id);
CREATE INDEX IF NOT EXISTS idx_curriculum_rec_status ON curriculum_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_rec_subjects_rec ON recommendation_subjects(recommendation_id);
CREATE INDEX IF NOT EXISTS idx_rec_objectives_subject ON recommendation_objectives(subject_id);
CREATE INDEX IF NOT EXISTS idx_rec_objectives_rec ON recommendation_objectives(recommendation_id);
CREATE INDEX IF NOT EXISTS idx_rec_objectives_status ON recommendation_objectives(status);
CREATE INDEX IF NOT EXISTS idx_advisor_chat_user ON advisor_chat_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_advisor_chat_child ON advisor_chat_messages(child_id);
CREATE INDEX IF NOT EXISTS idx_state_filing_types_state ON state_filing_types(state_abbreviation);
