/**
 * Shared @react-pdf/renderer primitives for Phase 8 filing templates.
 *
 * Every filing PDF carries:
 *  - A per-page footer with provenance ("Generated by AtoZ Family on…")
 *    so an evaluator or district admin can see the data version.
 *  - A first-page disclaimer block specific to the state + citation.
 *  - A "this is not legal advice" footer note.
 */

import {
  Document,
  Page as RPDFPage,
  StyleSheet,
  Text,
  View,
  type DocumentProps,
} from "@react-pdf/renderer"
import type { FilingSnapshot, FilingTypeMeta } from "./types"

export const palette = {
  ink: "#161817",
  ink2: "#4a4d4c",
  ink3: "#75787a",
  ink4: "#9aa0a3",
  rule: "#d8d9d7",
  sage: "#556b47",
  terracotta: "#a44830",
} as const

export const baseStyles = StyleSheet.create({
  page: {
    padding: 56,
    paddingBottom: 96, // room for footer
    fontFamily: "Helvetica",
    fontSize: 11,
    color: palette.ink,
    lineHeight: 1.4,
  },
  eyebrow: {
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 2,
    color: palette.ink3,
    marginBottom: 6,
  },
  h1: {
    fontSize: 22,
    fontWeight: "normal",
    marginBottom: 4,
    color: palette.ink,
  },
  h2: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 18,
    marginBottom: 6,
    color: palette.ink,
  },
  subdued: {
    color: palette.ink3,
    fontSize: 10,
  },
  block: { marginBottom: 12 },
  row: { flexDirection: "row", marginBottom: 4 },
  rowLabel: { width: 130, color: palette.ink2 },
  rowValue: { flex: 1 },
  disclaimerBox: {
    marginTop: 18,
    padding: 12,
    border: `1pt solid ${palette.rule}`,
    fontSize: 9,
    color: palette.ink2,
    lineHeight: 1.4,
  },
  signature: {
    marginTop: 36,
    paddingTop: 10,
    borderTop: `1pt solid ${palette.rule}`,
    fontSize: 10,
    color: palette.ink2,
  },
  footer: {
    position: "absolute",
    bottom: 40,
    left: 56,
    right: 56,
    fontSize: 8,
    color: palette.ink4,
    textAlign: "center",
    lineHeight: 1.4,
  },
})

export function FilingFooter({ snapshot }: { snapshot: FilingSnapshot }) {
  const generated = new Date(snapshot.generatedAt).toISOString().slice(0, 10)
  const rulesAsOf = snapshot.rulesVersion ?? "n/a"
  return (
    <View style={baseStyles.footer} fixed>
      <Text>
        Generated by AtoZ Family on {generated} · State rules as of {rulesAsOf} ·{" "}
        Record-keeping tool, not legal advice — verify your state's current requirements before submitting.
      </Text>
    </View>
  )
}

export function FilingHeader({
  meta,
  schoolYear,
}: {
  meta: FilingTypeMeta
  schoolYear: string
}) {
  return (
    <View style={baseStyles.block}>
      <Text style={baseStyles.eyebrow}>{meta.state.toUpperCase()} · {meta.filingType}</Text>
      <Text style={baseStyles.h1}>{meta.title}</Text>
      <Text style={baseStyles.subdued}>
        School year {schoolYear} · For: {meta.recipient}
      </Text>
    </View>
  )
}

export function FilingDisclaimer({
  meta,
  snapshot,
}: {
  meta: FilingTypeMeta
  snapshot: FilingSnapshot
}) {
  return (
    <View style={baseStyles.disclaimerBox}>
      <Text>
        This {meta.title.toLowerCase()} reflects {meta.state.toUpperCase()}'s requirements under {meta.citation},
        as last reviewed {snapshot.rulesVersion ?? "(date not stamped)"}. Statutes change. Confirm with your{" "}
        {meta.recipient.toLowerCase()} that the format is currently accepted before relying on this filing.
        AtoZ Family is a record-keeping tool and does not provide legal advice.
      </Text>
    </View>
  )
}

export interface FilingDocumentProps extends Omit<DocumentProps, "children"> {
  children: React.ReactNode
}

export function FilingDocument({ children, ...rest }: FilingDocumentProps) {
  return <Document {...rest}>{children}</Document>
}

export { RPDFPage as Page, Text, View, StyleSheet }
